Config = {}

Config.ItemCategories = {
    Weapons = {
		"WEAPON_PISTOL",
		"WEAPON_SMG",
		"WEAPON_SNSPISTOL",
		"WEAPON_SPECIALCARBINE",
		"WEAPON_COMPACTRIFLE",
		"WEAPON_MINIGUN",
		"WEAPON_HEAVYSHOTGUN",
		"WEAPON_COMBATMG",
		"WEAPON_SMOKEGRENADE",
		"WEAPON_BZGAS",
		"WEAPON_STUNGUN",
		"WEAPON_MARKSMANPISTOL",
		"WEAPON_CARBINERIFLE",
		"WEAPON_COMBATPDW",
		"WEAPON_DBSHOTGUN",
		"WEAPON_APPISTOL",
		"WEAPON_HEAVYSNIPER",
		"WEAPON_MUSKET",
		"WEAPON_ADVANCEDRIFLE",
		"WEAPON_MARKSMANRIFLE",
		"WEAPON_STICKYBOMB",
		"WEAPON_ASSAULTSHOTGUN",
		"WEAPON_COMBATPISTOL",
		"WEAPON_DOUBLEACTION",
		"WEAPON_VINTAGEPISTOL",
		"WEAPON_MACHINEPISTOL",
		"WEAPON_SNIPERRIFLE",
		"WEAPON_ASSAULTRIFLE",
		"WEAPON_MOLOTOV",
		"WEAPON_GUSENBERG"
	},
	Consumables = {
		"COCACOLA",
	},
	Drugs = {
		"CLOTH",
		"COCAINE",
		"CANNABIS"
	}
}